//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationusingcurd.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEmpclass", Namespace="http://tempuri.org/", ItemName="empclass")]
    [System.SerializableAttribute()]
    public class ArrayOfEmpclass : System.Collections.Generic.List<applicationusingcurd.ServiceReference1.empclass> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="empclass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class empclass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string e_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string e_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string e_designationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string e_id {
            get {
                return this.e_idField;
            }
            set {
                if ((object.ReferenceEquals(this.e_idField, value) != true)) {
                    this.e_idField = value;
                    this.RaisePropertyChanged("e_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string e_name {
            get {
                return this.e_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.e_nameField, value) != true)) {
                    this.e_nameField = value;
                    this.RaisePropertyChanged("e_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string e_designation {
            get {
                return this.e_designationField;
            }
            set {
                if ((object.ReferenceEquals(this.e_designationField, value) != true)) {
                    this.e_designationField = value;
                    this.RaisePropertyChanged("e_designation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EmployeeSoap")]
    public interface EmployeeSoap {
        
        // CODEGEN: Generating message contract since element name e_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/employeeadd", ReplyAction="*")]
        applicationusingcurd.ServiceReference1.employeeaddResponse employeeadd(applicationusingcurd.ServiceReference1.employeeaddRequest request);
        
        // CODEGEN: Generating message contract since element name e_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_employee", ReplyAction="*")]
        applicationusingcurd.ServiceReference1.update_employeeResponse update_employee(applicationusingcurd.ServiceReference1.update_employeeRequest request);
        
        // CODEGEN: Generating message contract since element name e_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteemployee", ReplyAction="*")]
        applicationusingcurd.ServiceReference1.deleteemployeeResponse deleteemployee(applicationusingcurd.ServiceReference1.deleteemployeeRequest request);
        
        // CODEGEN: Generating message contract since element name bindsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binds", ReplyAction="*")]
        applicationusingcurd.ServiceReference1.bindsResponse binds(applicationusingcurd.ServiceReference1.bindsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class employeeaddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="employeeadd", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.employeeaddRequestBody Body;
        
        public employeeaddRequest() {
        }
        
        public employeeaddRequest(applicationusingcurd.ServiceReference1.employeeaddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class employeeaddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string e_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string e_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string e_designation;
        
        public employeeaddRequestBody() {
        }
        
        public employeeaddRequestBody(string e_id, string e_name, string e_designation) {
            this.e_id = e_id;
            this.e_name = e_name;
            this.e_designation = e_designation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class employeeaddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="employeeaddResponse", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.employeeaddResponseBody Body;
        
        public employeeaddResponse() {
        }
        
        public employeeaddResponse(applicationusingcurd.ServiceReference1.employeeaddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class employeeaddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string employeeaddResult;
        
        public employeeaddResponseBody() {
        }
        
        public employeeaddResponseBody(string employeeaddResult) {
            this.employeeaddResult = employeeaddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_employeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_employee", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.update_employeeRequestBody Body;
        
        public update_employeeRequest() {
        }
        
        public update_employeeRequest(applicationusingcurd.ServiceReference1.update_employeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_employeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string e_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string e_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string e_designation;
        
        public update_employeeRequestBody() {
        }
        
        public update_employeeRequestBody(string e_id, string e_name, string e_designation) {
            this.e_id = e_id;
            this.e_name = e_name;
            this.e_designation = e_designation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_employeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_employeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.update_employeeResponseBody Body;
        
        public update_employeeResponse() {
        }
        
        public update_employeeResponse(applicationusingcurd.ServiceReference1.update_employeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_employeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string update_employeeResult;
        
        public update_employeeResponseBody() {
        }
        
        public update_employeeResponseBody(string update_employeeResult) {
            this.update_employeeResult = update_employeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteemployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteemployee", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.deleteemployeeRequestBody Body;
        
        public deleteemployeeRequest() {
        }
        
        public deleteemployeeRequest(applicationusingcurd.ServiceReference1.deleteemployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteemployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string e_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string e_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string e_designation;
        
        public deleteemployeeRequestBody() {
        }
        
        public deleteemployeeRequestBody(string e_id, string e_name, string e_designation) {
            this.e_id = e_id;
            this.e_name = e_name;
            this.e_designation = e_designation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteemployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteemployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.deleteemployeeResponseBody Body;
        
        public deleteemployeeResponse() {
        }
        
        public deleteemployeeResponse(applicationusingcurd.ServiceReference1.deleteemployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteemployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteemployeeResult;
        
        public deleteemployeeResponseBody() {
        }
        
        public deleteemployeeResponseBody(string deleteemployeeResult) {
            this.deleteemployeeResult = deleteemployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bindsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binds", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.bindsRequestBody Body;
        
        public bindsRequest() {
        }
        
        public bindsRequest(applicationusingcurd.ServiceReference1.bindsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class bindsRequestBody {
        
        public bindsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bindsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bindsResponse", Namespace="http://tempuri.org/", Order=0)]
        public applicationusingcurd.ServiceReference1.bindsResponseBody Body;
        
        public bindsResponse() {
        }
        
        public bindsResponse(applicationusingcurd.ServiceReference1.bindsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bindsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public applicationusingcurd.ServiceReference1.ArrayOfEmpclass bindsResult;
        
        public bindsResponseBody() {
        }
        
        public bindsResponseBody(applicationusingcurd.ServiceReference1.ArrayOfEmpclass bindsResult) {
            this.bindsResult = bindsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeSoapChannel : applicationusingcurd.ServiceReference1.EmployeeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeSoapClient : System.ServiceModel.ClientBase<applicationusingcurd.ServiceReference1.EmployeeSoap>, applicationusingcurd.ServiceReference1.EmployeeSoap {
        
        public EmployeeSoapClient() {
        }
        
        public EmployeeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        applicationusingcurd.ServiceReference1.employeeaddResponse applicationusingcurd.ServiceReference1.EmployeeSoap.employeeadd(applicationusingcurd.ServiceReference1.employeeaddRequest request) {
            return base.Channel.employeeadd(request);
        }
        
        public string employeeadd(string e_id, string e_name, string e_designation) {
            applicationusingcurd.ServiceReference1.employeeaddRequest inValue = new applicationusingcurd.ServiceReference1.employeeaddRequest();
            inValue.Body = new applicationusingcurd.ServiceReference1.employeeaddRequestBody();
            inValue.Body.e_id = e_id;
            inValue.Body.e_name = e_name;
            inValue.Body.e_designation = e_designation;
            applicationusingcurd.ServiceReference1.employeeaddResponse retVal = ((applicationusingcurd.ServiceReference1.EmployeeSoap)(this)).employeeadd(inValue);
            return retVal.Body.employeeaddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        applicationusingcurd.ServiceReference1.update_employeeResponse applicationusingcurd.ServiceReference1.EmployeeSoap.update_employee(applicationusingcurd.ServiceReference1.update_employeeRequest request) {
            return base.Channel.update_employee(request);
        }
        
        public string update_employee(string e_id, string e_name, string e_designation) {
            applicationusingcurd.ServiceReference1.update_employeeRequest inValue = new applicationusingcurd.ServiceReference1.update_employeeRequest();
            inValue.Body = new applicationusingcurd.ServiceReference1.update_employeeRequestBody();
            inValue.Body.e_id = e_id;
            inValue.Body.e_name = e_name;
            inValue.Body.e_designation = e_designation;
            applicationusingcurd.ServiceReference1.update_employeeResponse retVal = ((applicationusingcurd.ServiceReference1.EmployeeSoap)(this)).update_employee(inValue);
            return retVal.Body.update_employeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        applicationusingcurd.ServiceReference1.deleteemployeeResponse applicationusingcurd.ServiceReference1.EmployeeSoap.deleteemployee(applicationusingcurd.ServiceReference1.deleteemployeeRequest request) {
            return base.Channel.deleteemployee(request);
        }
        
        public string deleteemployee(string e_id, string e_name, string e_designation) {
            applicationusingcurd.ServiceReference1.deleteemployeeRequest inValue = new applicationusingcurd.ServiceReference1.deleteemployeeRequest();
            inValue.Body = new applicationusingcurd.ServiceReference1.deleteemployeeRequestBody();
            inValue.Body.e_id = e_id;
            inValue.Body.e_name = e_name;
            inValue.Body.e_designation = e_designation;
            applicationusingcurd.ServiceReference1.deleteemployeeResponse retVal = ((applicationusingcurd.ServiceReference1.EmployeeSoap)(this)).deleteemployee(inValue);
            return retVal.Body.deleteemployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        applicationusingcurd.ServiceReference1.bindsResponse applicationusingcurd.ServiceReference1.EmployeeSoap.binds(applicationusingcurd.ServiceReference1.bindsRequest request) {
            return base.Channel.binds(request);
        }
        
        public applicationusingcurd.ServiceReference1.ArrayOfEmpclass binds() {
            applicationusingcurd.ServiceReference1.bindsRequest inValue = new applicationusingcurd.ServiceReference1.bindsRequest();
            inValue.Body = new applicationusingcurd.ServiceReference1.bindsRequestBody();
            applicationusingcurd.ServiceReference1.bindsResponse retVal = ((applicationusingcurd.ServiceReference1.EmployeeSoap)(this)).binds(inValue);
            return retVal.Body.bindsResult;
        }
    }
}
